name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { goos: linux,   goarch: amd64, runner: ubuntu-latest,  ext: ""    }
          - { goos: linux,   goarch: arm64, runner: ubuntu-latest,  ext: ""    }
          - { goos: darwin,  goarch: amd64, runner: macos-latest,   ext: ""    }
          - { goos: darwin,  goarch: arm64, runner: macos-latest,   ext: ""    }
          - { goos: windows, goarch: amd64, runner: windows-latest, ext: ".exe"}
          - { goos: windows, goarch: arm64, runner: windows-latest, ext: ".exe"}

    env:
      CGO_ENABLED: "0"
      VERSION: ${{ github.ref_name }}
      COMMIT: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set build date
        id: meta
        run: echo "DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build
        run: |
          mkdir -p dist
          OUT="dai${{ matrix.ext }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -trimpath -ldflags "-s -w \
            -X github.com/gorankrgovic/dai/internal/buildinfo.Version=${VERSION} \
            -X github.com/gorankrgovic/dai/internal/buildinfo.Commit=${COMMIT} \
            -X github.com/gorankrgovic/dai/internal/buildinfo.Date=${{ steps.meta.outputs.DATE }}" \
            -o "${OUT}" ./
          DIR="dai_${VERSION}_${{ matrix.goos }}-${{ matrix.goarch }}"
          mkdir -p "dist/${DIR}"
          mv "${OUT}" "dist/${DIR}/"
          echo "DAI ${VERSION} (${{ matrix.goos }}-${{ matrix.goarch }})" > "dist/${DIR}/README.txt"
        shell: bash

      - name: Archive
        run: |
          cd dist
          DIR="dai_${VERSION}_${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            7z a "${DIR}.zip" "${DIR}" > /dev/null
          else
            tar -C . -czf "${DIR}.tar.gz" "${DIR}"
          fi
        shell: bash

      - name: Checksums
        run: |
          cd dist
          if ls dai_${VERSION}_${{ matrix.goos }}-${{ matrix.goarch }}.* >/dev/null 2>&1; then
            for f in dai_${VERSION}_${{ matrix.goos }}-${{ matrix.goarch }}.*; do
              if command -v shasum >/dev/null 2>&1; then
                shasum -a 256 "$f" | awk '{print $1 "  " FILENAME}' FILENAME="$f" >> checksums-${{ matrix.goos }}-${{ matrix.goarch }}.txt
              else
                sha256sum "$f" >> checksums-${{ matrix.goos }}-${{ matrix.goarch }}.txt
              fi
            done
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dai_${{ env.VERSION }}_${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            dist/dai_${{ env.VERSION }}_${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
            dist/dai_${{ env.VERSION }}_${{ matrix.goos }}-${{ matrix.goarch }}.zip
            dist/checksums-*.txt
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout za changelog
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      # 2) Generate changelog
      - name: Generate changelog from commits
        run: |
          set -euo pipefail
          mkdir -p upload

          CUR="${GITHUB_REF_NAME}"
          PREV="$(git describe --tags --abbrev=0 "${CUR}^" 2>/dev/null || true)"
          if [ -z "${PREV}" ]; then
            RANGE="${CUR}"
            RANGE_HUMAN="initial"
          else
            RANGE="${PREV}..${CUR}"
            RANGE_HUMAN="${PREV}…${CUR}"
          fi

          {
            echo "# ${CUR}"
            echo
            echo "_Changes from ${RANGE_HUMAN}_"
            echo
            git log --no-merges --pretty=format:'- %s (%h)' ${RANGE} \
            | awk '
              function emit(title, arr,    i){ if(length(arr)>0){ print "### " title; for(i=1;i<=length(arr);i++) print arr[i]; print "" }}
              BEGIN{ nf=0; nfx=0; np=0; nr=0; nd=0; nc=0; nt=0; no=0 }
              {
                line=$0
                if (line ~ /^- (feat|feat!|\[feat\])/){ feat[++nf]=line }
                else if (line ~ /^- (fix|fix!|\[fix\])/){ fixes[++nfx]=line }
                else if (line ~ /^- (perf|perf!|\[perf\])/){ perf[++np]=line }
                else if (line ~ /^- (refactor|refactor!|\[refactor\])/){ refa[++nr]=line }
                else if (line ~ /^- (docs|docs!|\[docs\])/){ docs[++nd]=line }
                else if (line ~ /^- (chore|build)/){ chore[++nc]=line }
                else if (line ~ /^- (test|tests)/){ tests[++nt]=line }
                else { other[++no]=line }
              }
              END{
                emit("Features", feat)
                emit("Fixes", fixes)
                emit("Performance", perf)
                emit("Refactors", refa)
                emit("Docs", docs)
                emit("Chore/Build", chore)
                emit("Tests", tests)
                emit("Other", other)
              }'
          } > upload/CHANGELOG.md

      # 3) Preuzmi build artefakte
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      # 4) Pripremi fajlove za release
      - name: Gather files
        run: |
          set -euo pipefail
          mkdir -p upload
          shopt -s nullglob
          cp dist/dai_v*.tar.gz upload/ || true
          cp dist/dai_v*.zip upload/ || true
          cat dist/checksums-*.txt > upload/checksums.txt

          VERSION="${GITHUB_REF_NAME#v}"
          for f in upload/dai_v${VERSION}_*; do
            base="$(basename "$f")"
            alias="upload/${base/dai_v${VERSION}_/dai_}"
            cp -f "$f" "$alias"
          done

      - name: List collected files
        run: ls -la upload

      # 5) Kreiraj release u istom repo-u
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
          tag_name: ${{ github.ref_name }}
          body_path: upload/CHANGELOG.md
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}